version: '2'
services:
    automatiza7-app:
        image: automatiza7
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://automatiza7-mssql:1433;database=Automatiza7
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    automatiza7-mssql:
        extends:
            file: mssql.yml
            service: automatiza7-mssql
